require('plugins')
require('_lsp-config')
--require('navigator-config')
require('_lsp-config-emmet')
require('cmp-config')
require('treesitter-config')
require('colors')
require('generic-options')
require('keys')
require('search-options')
require('telescope-config')
require('statusline')
require('formatting')
require('vim-test')
vim.cmd('source ~/.config/nvim/keys.vim')
