require('plugins')
require('_lsp-config')
require('cmp-config')
require('treesitter-config')
require('colors')
require('generic-options')
require('keys')
require('search-options')
require('telescope-config')
require('statusline')

